export const cardsMock = [
  { point: 0, rank: 1, suit: "s", value: 1 },
  { point: 0, rank: 1, suit: "h", value: 2 },
  { point: 0, rank: 1, suit: "d", value: 3 },
  { point: 0, rank: 1, suit: "c", value: 4 },
  { point: 0, rank: 2, suit: "s", value: 1 },
  { point: 0, rank: 2, suit: "h", value: 2 },
  { point: 0, rank: 2, suit: "d", value: 3 },
  { point: 0, rank: 2, suit: "c", value: 4 },
  { point: 0, rank: 3, suit: "s", value: 1 },
  { point: 0, rank: 3, suit: "h", value: 2 },
  { point: 0, rank: 3, suit: "d", value: 3 },
  { point: 0, rank: 3, suit: "c", value: 4 },
  { point: 0, rank: 4, suit: "s", value: 1 },
  { point: 0, rank: 4, suit: "h", value: 2 },
  { point: 0, rank: 4, suit: "d", value: 3 },
  { point: 0, rank: 4, suit: "c", value: 4 },
  { point: 0, rank: 5, suit: "s", value: 1 },
  { point: 0, rank: 5, suit: "h", value: 2 },
  { point: 0, rank: 5, suit: "d", value: 3 },
  { point: 0, rank: 5, suit: "c", value: 4 },
  { point: 0, rank: 6, suit: "s", value: 1 },
  { point: 0, rank: 6, suit: "h", value: 2 },
  { point: 0, rank: 6, suit: "d", value: 3 },
  { point: 0, rank: 6, suit: "c", value: 4 },
  { point: 0, rank: 7, suit: "s", value: 1 },
  { point: 0, rank: 7, suit: "h", value: 2 },
  { point: 0, rank: 7, suit: "d", value: 3 },
  { point: 0, rank: 7, suit: "c", value: 4 },
  { point: 0, rank: 8, suit: "s", value: 1 },
  { point: 0, rank: 8, suit: "h", value: 2 },
  { point: 0, rank: 8, suit: "d", value: 3 },
  { point: 0, rank: 8, suit: "c", value: 4 },
  { point: 0, rank: 9, suit: "s", value: 1 },
  { point: 0, rank: 9, suit: "h", value: 2 },
  { point: 0, rank: 9, suit: "d", value: 3 },
  { point: 0, rank: 9, suit: "c", value: 4 },
  { point: 1, rank: 10, suit: "s", value: 1 },
  { point: 1, rank: 10, suit: "h", value: 2 },
  { point: 1, rank: 10, suit: "d", value: 3 },
  { point: 1, rank: 10, suit: "c", value: 4 },
  { point: 2, rank: 11, suit: "s", value: 1 },
  { point: 2, rank: 11, suit: "h", value: 2 },
  { point: 2, rank: 11, suit: "d", value: 3 },
  { point: 2, rank: 11, suit: "c", value: 4 },
  { point: 3, rank: 12, suit: "s", value: 1 },
  { point: 3, rank: 12, suit: "h", value: 2 },
  { point: 3, rank: 12, suit: "d", value: 3 },
  { point: 3, rank: 12, suit: "c", value: 4 },
  { point: 4, rank: 13, suit: "s", value: 1 },
  { point: 4, rank: 13, suit: "h", value: 2 },
  { point: 4, rank: 13, suit: "d", value: 3 },
  { point: 4, rank: 13, suit: "c", value: 4 }
];
export const seatsMock = [
  {
    id: "n",assertPoints:14, cards: [
      { id: 0, data: { point: 0, rank: 1, suit: "s", value: 1 }},
      { id: 1, data: { point: 0, rank: 7, suit: "s", value: 1 }},
      { id: 2, data: { point: 4, rank: 13, suit: "d", value: 3 }},
      { id: 3, data: { point: 4, rank: 13, suit: "c", value: 4 }},
      { id: 4, data: { point: 0, rank: 9, suit: "h", value: 2 }},
      { id: 5, data: { point: 1, rank: 10, suit: "d", value: 3 }},
      { id: 6, data: { point: 0, rank: 6, suit: "s", value: 1 }},
      { id: 7, data: { point: 0, rank: 8, suit: "h", value: 2 }},
      { id: 8, data: { point: 0, rank: 8, suit: "s", value: 1 }},
      { id: 9, data: { point: 0, rank: 5, suit: "d", value: 3 }},
      { id: 10, data: { point: 3, rank: 12, suit: "c", value: 4 }},
      { id: 11, data: { point: 0, rank: 9, suit: "c", value: 4 }},
      { id: 12, data: { point: 2, rank: 11, suit: "d", value: 3 }}
    ]
  }
]
